trying if command

diff --git a/.github/workflows/python-test.yml b/.github/workflows/python-test.yml
--- a/.github/workflows/python-test.yml
+++ b/.github/workflows/python-test.yml
@@ -38,19 +38,27 @@ jobs:
     - name: Test
       run: |
         python3 rtest.py Cree
+      continue-on-error: true 
     - name: Upload test logs as artifact
+      if: always()
       uses: actions/upload-artifact@v3
       with:
         name: test-logs
         path: /home/runner/work/matrix/matrix/tests/regression/logs/*
-  logs:
-    runs-on: ubuntu-latest
-    needs: [build-and-test]
-    steps:
-    - name: Download test logs from previous job
-      uses: actions/download-artifact@v3
-      with:
-        name: test-logs
-    - name: View the test logs
+    - name: Fail the job if the tests failed
+      if: failure()
       run: |
-        ls -l work/matrix/matrix/tests/regression/logs/*
+        echo "Tests failed. Check logs for details."
+        exit 1
+
+  # logs:
+  #   runs-on: ubuntu-latest
+  #   needs: [build-and-test]
+  #   steps:
+  #   - name: Download test logs from previous job
+  #     uses: actions/download-artifact@v3
+  #     with:
+  #       name: test-logs
+  #   - name: View the test logs
+  #     run: |
+  #       ls -l work/matrix/matrix/tests/regression/logs/*
